# Generated by Django 6.0.2 on 2026-02-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_zip',
            field=models.FileField(blank=True, null=True, upload_to='project_zips/'),
        ),
        migrations.AddField(
            model_name='project',
            name='coding_env_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_desc',
            field=models.CharField(max_length=300),
        ),
    ]
