# Generated by Django 6.0.2 on 2026-02-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_code_zip_project_coding_env_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
