# Generated by Django 6.0.2 on 2026-02-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='show_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='show_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='show_short_desc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='show_youtube',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='show_zip',
            field=models.BooleanField(default=True),
        ),
    ]
