# Generated by Django 6.0.2 on 2026-02-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_author_name_alter_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='show_code',
            field=models.BooleanField(default=True),
        ),
    ]
